---
title: "간단한 설문조사 데이터 전처리"
description: |
  이번 장에서는 간단한 실제 설문조사 데이터를 가지고 데이터 전처리를 해본다. 사용 할 데이터는 다음 주소에서 다운로드 받을 수 있다(http://web-r.org/index.php?mid=book&documentsrl=31924). 이 데이터는 성빈센트병원에서 제 5회 QI(Quality Improvement) Academy 가 끝난 후 시행한 평가 설문지 데이터로 설문 내용은 “설문지.docx”이다. 먼저 설문지코딩.xlsx 파일을 살펴보자.
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r chapter-2, results='asis'}
library(tidyverse)
library(officer)

webr_docx <- officer::read_docx("data/webr.docx")
webr_content <- docx_summary(webr_docx) %>% 
  as_tibble()

ch01_start_idx <- which(webr_content$text == "제 1 장")
ch02_start_idx <- which(webr_content$text == "제 2 장")
ch03_start_idx <- which(webr_content$text == "제 3 장")

ch02_raw <- webr_content %>% 
  mutate(text = str_remove(text, pattern = "\\d{15}")) %>% 
  filter(between(row_number(), ch02_start_idx, ch03_start_idx - 1)) %>% 
  filter(!text == "") %>% 
  select(style_name, text)

ch02_md <- ch02_raw %>% 
  filter(!str_detect(text, "제\\s?[0-9]\\s?장")) %>% 
  slice(3:n()) %>%   
  mutate(markdown = case_when(style_name == "heading 1"             ~ glue::glue("# {text} \n\n"),
                              str_detect(text, "제\\s?[0-9]+\\s?절") ~ glue::glue("## {text} \n\n"),
                              style_name == "heading 3"             ~ glue::glue("### {text} \n\n"),
                              TRUE                                  ~ glue::glue("{text} \n\n"))) %>% 
  pull(markdown)

print(ch02_md)

```

# 그림과 그래프

```{r images-slickr-ch02, eval = TRUE}
library(slickR)

webr_img <- fs::dir_ls(path = "data/images/", glob = "*.png")

webr_tbl <- tibble(fig = glue::glue("{webr_img}") )

ch2_img_tbl <- webr_tbl %>% 
  mutate(page = str_extract(fig, pattern = "\\d+") %>% as.integer) %>% 
  filter(page %% 2 == 0) %>% 
  filter(page >= 34 & page <=62)
  
slickR(ch2_img_tbl$fig, height = 600)
```


