---
title: "웹에서 하는 R 통계분석"
description: |
  상용 통계 팩키지를 통해 수행되던 많은 통계 분석 작업이 이제는 "웹에서 하는 R 통계분석"을 통해 누구나 접근하여 활용할 수 있게 되었습니다. 특히 저자이시고 직접 웹R을 개발하신 문건웅 교수님이 "웹R을 이용한 통계분석" 책을 원하는 분들이 많아 [leanpub](https://leanpub.com/webr) 을 통해 pdf형식으로 출간되어 누구나 활용할 수 있도록 배포해주셨습니다.
site: distill::distill_website
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

# 머릿말

```{r webr-preface}
library(tidyverse)
webr_preface <- read_rds("data/webr_preface.rds")

webr_preface_tbl <- tribble( ~"머릿말",
                             webr_preface)
webr_preface_tbl %>% 
  reactable::reactable()
```

# 목차 

```{r webr-toc}
library(collapsibleTree)

webr_toc_tbl  <-  read_rds(glue::glue("{here::here()}/data/webr_toc_tbl.rds"))

# webr_toc_tbl %>% 
#   reactable::reactable()

collapsibleTree(webr_toc_tbl, 
                hierarchy  = c("subtitle", "subsubtitle"),
                root       = "웹R 통계분석",
                tooltip    = TRUE,
                attributes = "title",
                fill       = "#64ABC2",
                collapsed  = TRUE, 
                width      = 800,
                zoomable   = FALSE)
```

# 웹R을 이용한 통계분석 최신판

- [웹R을 이용한 통계분석 2020](https://bookdown.org/cardiomoon/webrbook2020/)

# `web-r` 접속 {#web-r-website}

<http://web-r.org/>

## 정회원 접속서버 {#main-features}

1. 웹에서 하는 R 통계 4.0 정회원용
 
- <https://cardiomoon.shinyapps.io/webr>
- <https://cardiomoon.shinyapps.io/webr1>
- <https://cardiomoon.shinyapps.io/webr2>
  
2. 웹에서 하는 R 통계 4.0 중 생존분석과 PSM
 
- <https://cardiomoon.shinyapps.io/survival>
- <https://cardiomoon.shinyapps.io/survival1>
 
3. 조건부과정분석

- <https://cardiomoon.shinyapps.io/processR>
 
4. ROC 분석, Classification (Decision tree, Survival tree), Reclassification(NRI,IDI), AutomaticTransformation
 
- <https://cardiomoon.shinyapps.io/webrROC>
 
5. 메타분석
 
- <https://cardiomoon.shinyapps.io/metaNew>
 
6. PubMed wordcloud
 
- <https://cardiomoon.shinyapps.io/pubmed>

